version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finextra
    volumes:
      - finextra:/var/lib/postgresql/data
    networks:
      finextranet:
    container_name: "finextra-db"
  frontend:
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - db
    links:
      - "db:db"
    networks:
      finextranet:
    container_name: "finextra-frontend"

volumes:
  finextra:

networks:
  finextranet:
    driver: bridge
